### PR TITLE
Header length verification correction

### PR DESCRIPTION
**Pull request by corwin-of-amber**
This has been noticed in https://github.com/vasi/qcow2-fuse/issues/4.

The fix seems to alleviate the problem.

This is a cool and useful project! Please respond 🍰☺️

### CODE REVIEW

**Comment by vasi** [comment]
Awesome, thanks!

**Comment by niklasha** [comment]
Unfortunately, this fix is wrong.  According to [Qemu source](https://github.com/qemu/qemu/blob/54e1f5be86dd11744e45da8be6afad01d01d59e7/block/qcow2.c#L1610) and indeed [QCOW2 specification](https://github.com/qemu/qemu/blob/48033ad678ae2def43bf0d543a2c4c3d2a93feaf/docs/interop/qcow2.txt#L228)  (although not very explicit, but it is evident when reading on that header extensions are not part of the header struct) the header_length do *not* include the extensions.  The fundamental problem is that the qcow2 crate does not handle "additional fields" at all.  This is easily fixed.

I will soon submit a pull request to fix this properly for review.

**Comment by corwin-of-amber** [comment]
I was indeed a bit doubtful -- thanks for digging deeper @niklasha 👍

**Comment by vasi** [comment]
Thanks for looking into this!

**Pull request merged**
